@baseUrl = http://localhost:8088/Plone

###

get {{baseUrl}}/sample-page
Authorization: Basic admin:admin

###

post {{baseUrl}}/@querystring-search
Authorization: Basic admin:admin
content-type: application/json

{
    "query": [
        {
            "i": "portal_type",
            "o": "plone.app.querystring.operation.selection.any",
            "v": [
                "File"
            ]
        },
        {
            "i": "review_state",
            "o": "plone.app.querystring.operation.selection.any",
            "v": [
                "reviewed"
            ]
        }
    ]
}


###

get {{baseUrl}}/@vocabularies
Authorization: Basic admin:admin

###

get {{baseUrl}}/@vocabularies/plone.app.vocabularies.PortalTypes?b_size=100
Authorization: Basic admin:admin
